web:
  image: abramm/d8-dev-web:latest
  ports:
    - "8000:80"
  links:
    - mysql
  volumes:
    - ./data/htdocs:/var/www/html
    - ./dummyfile:/tmp/dummyfile
  hostname: d8-dev-web
mysql:
  image: mysql
  volumes:
    - ./data/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: d8-dev
    MYSQL_DATABASE: drupal
    MYSQL_USER: drupal
    MYSQL_PASSWORD: password
    
