web:
  image: andriyun/d8-dev-web
  ports:
    - "80:80"
  links:
    - mysql
  volumes:
    - ./data/htdocs:/var/www/html
    - ./dummyfile:/tmp/dummyfile
  hostname: d8-dev-web
mysql:
  image: mysql
  volumes:
    - ./data/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: drupal
    MYSQL_USER: drupal
    MYSQL_PASSWORD: password
phpmyadmin:
  image: nazarpc/phpmyadmin
  links:
    - mysql
  ports:
    - "8001:80"

